
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'Bool Booleano Char CharAux Comentario Entero F64 False Float I64 Id Let Mut Str StrA String True diferenteQue dividido dobleIgual dosPuntos igual llaveA llaveC mas mayorQue menorQue menos parA parC por ptComainit : INSTRUCCIONESINSTRUCCIONES : INSTRUCCIONES INSTRUCCIONINSTRUCCIONES : INSTRUCCIONINSTRUCCION : DECLARACIONDECLARACION : Let Id igual EXPRESION ptComaDECLARACION : Let Id dosPuntos I64 igual EXPRESION ptComaDECLARACION : Let Id dosPuntos F64 igual EXPRESION ptComaDECLARACION : Let Id dosPuntos Str igual EXPRESION ptComa\n                    | Let Id dosPuntos StrA igual EXPRESION ptComaDECLARACION : Let Id dosPuntos Bool igual EXPRESION ptComaDECLARACION : Let Id dosPuntos CharAux igual EXPRESION ptComaDECLARACION : Let Mut Id igual EXPRESION ptComaDECLARACION : Let Mut Id dosPuntos I64 igual EXPRESION ptComaDECLARACION : Let Mut Id dosPuntos F64 igual EXPRESION ptComaDECLARACION : Let Mut Id dosPuntos Str igual EXPRESION ptComa\n                    | Let Mut Id dosPuntos StrA igual EXPRESION ptComaDECLARACION : Let Mut Id dosPuntos Bool igual EXPRESION ptComaDECLARACION : Let Mut Id dosPuntos CharAux igual EXPRESION ptComaINSTRUCCION : ASIGNACIONASIGNACION : Id igual EXPRESION ptComaEXPRESION : FloatEXPRESION : EnteroEXPRESION : BooleanoEXPRESION : StringEXPRESION : Char'
    
_lr_action_items = {'Let':([0,2,3,4,5,8,30,31,51,58,59,60,61,62,63,70,71,72,73,74,75,],[6,6,-3,-4,-19,-2,-20,-5,-12,-6,-7,-8,-9,-10,-11,-13,-14,-15,-16,-17,-18,]),'Id':([0,2,3,4,5,6,8,10,30,31,51,58,59,60,61,62,63,70,71,72,73,74,75,],[7,7,-3,-4,-19,9,-2,14,-20,-5,-12,-6,-7,-8,-9,-10,-11,-13,-14,-15,-16,-17,-18,]),'$end':([1,2,3,4,5,8,30,31,51,58,59,60,61,62,63,70,71,72,73,74,75,],[0,-1,-3,-4,-19,-2,-20,-5,-12,-6,-7,-8,-9,-10,-11,-13,-14,-15,-16,-17,-18,]),'Mut':([6,],[10,]),'igual':([7,9,14,22,23,24,25,26,27,39,40,41,42,43,44,],[11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,]),'dosPuntos':([9,14,],[13,29,]),'Float':([11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,],[16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,]),'Entero':([11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,],[17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,]),'Booleano':([11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,],[18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,]),'String':([11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,],[19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,]),'Char':([11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,],[20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,]),'I64':([13,29,],[22,39,]),'F64':([13,29,],[23,40,]),'Str':([13,29,],[24,41,]),'StrA':([13,29,],[25,42,]),'Bool':([13,29,],[26,43,]),'CharAux':([13,29,],[27,44,]),'ptComa':([15,16,17,18,19,20,21,38,45,46,47,48,49,50,64,65,66,67,68,69,],[30,-21,-22,-23,-24,-25,31,51,58,59,60,61,62,63,70,71,72,73,74,75,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'INSTRUCCIONES':([0,],[2,]),'INSTRUCCION':([0,2,],[3,8,]),'DECLARACION':([0,2,],[4,4,]),'ASIGNACION':([0,2,],[5,5,]),'EXPRESION':([11,12,28,32,33,34,35,36,37,52,53,54,55,56,57,],[15,21,38,45,46,47,48,49,50,64,65,66,67,68,69,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> INSTRUCCIONES','init',1,'p_init','gramatica.py',137),
  ('INSTRUCCIONES -> INSTRUCCIONES INSTRUCCION','INSTRUCCIONES',2,'p_listaInstrucciones','gramatica.py',141),
  ('INSTRUCCIONES -> INSTRUCCION','INSTRUCCIONES',1,'p_listaInstrucciones_Instruccion','gramatica.py',146),
  ('INSTRUCCION -> DECLARACION','INSTRUCCION',1,'p_Instruccion_Declaracion','gramatica.py',152),
  ('DECLARACION -> Let Id igual EXPRESION ptComa','DECLARACION',5,'p_Declaracion_Normal','gramatica.py',156),
  ('DECLARACION -> Let Id dosPuntos I64 igual EXPRESION ptComa','DECLARACION',7,'p_Declaracion_Normal_Tipo_I64','gramatica.py',160),
  ('DECLARACION -> Let Id dosPuntos F64 igual EXPRESION ptComa','DECLARACION',7,'p_Declaracion_Normal_Tipo_F64','gramatica.py',164),
  ('DECLARACION -> Let Id dosPuntos Str igual EXPRESION ptComa','DECLARACION',7,'p_Declaracion_Normal_Tipo_String','gramatica.py',168),
  ('DECLARACION -> Let Id dosPuntos StrA igual EXPRESION ptComa','DECLARACION',7,'p_Declaracion_Normal_Tipo_String','gramatica.py',169),
  ('DECLARACION -> Let Id dosPuntos Bool igual EXPRESION ptComa','DECLARACION',7,'p_Declaracion_Normal_Tipo_Bool','gramatica.py',173),
  ('DECLARACION -> Let Id dosPuntos CharAux igual EXPRESION ptComa','DECLARACION',7,'p_Declaracion_Normal_Tipo_Char','gramatica.py',177),
  ('DECLARACION -> Let Mut Id igual EXPRESION ptComa','DECLARACION',6,'p_Declaracion_Mut','gramatica.py',181),
  ('DECLARACION -> Let Mut Id dosPuntos I64 igual EXPRESION ptComa','DECLARACION',8,'p_Declaracion_Mut_Tipo_I64','gramatica.py',186),
  ('DECLARACION -> Let Mut Id dosPuntos F64 igual EXPRESION ptComa','DECLARACION',8,'p_Declaracion_Mut_Tipo_F64','gramatica.py',190),
  ('DECLARACION -> Let Mut Id dosPuntos Str igual EXPRESION ptComa','DECLARACION',8,'p_Declaracion_Mut_Tipo_String','gramatica.py',194),
  ('DECLARACION -> Let Mut Id dosPuntos StrA igual EXPRESION ptComa','DECLARACION',8,'p_Declaracion_Mut_Tipo_String','gramatica.py',195),
  ('DECLARACION -> Let Mut Id dosPuntos Bool igual EXPRESION ptComa','DECLARACION',8,'p_Declaracion_Mut_Tipo_Bool','gramatica.py',199),
  ('DECLARACION -> Let Mut Id dosPuntos CharAux igual EXPRESION ptComa','DECLARACION',8,'p_Declaracion_Mut_Tipo_Char','gramatica.py',203),
  ('INSTRUCCION -> ASIGNACION','INSTRUCCION',1,'p_Instruccion_Asignacion','gramatica.py',209),
  ('ASIGNACION -> Id igual EXPRESION ptComa','ASIGNACION',4,'p_Asignacion','gramatica.py',213),
  ('EXPRESION -> Float','EXPRESION',1,'p_Expresion_Float','gramatica.py',219),
  ('EXPRESION -> Entero','EXPRESION',1,'p_Expresion_Entero','gramatica.py',223),
  ('EXPRESION -> Booleano','EXPRESION',1,'p_Expresion_Booleano','gramatica.py',227),
  ('EXPRESION -> String','EXPRESION',1,'p_Expresion_String','gramatica.py',231),
  ('EXPRESION -> Char','EXPRESION',1,'p_Expresion_Char','gramatica.py',235),
]
